CREATE TABLE MOVIE(
ID NUMBER,
CONSTRAINT MOVIE_ID PRIMARY KEY(ID),
TITLE NVARCHAR2(50) UNIQUE,
DIRECTOR NVARCHAR2(50),
YEAR NUMBER(4) CHECK(YEAR>=1900 AND YEAR <=2018),
LENGTH_MINS NUMBER CHECK(LENGTH_MINS>=10 AND LENGTH_MINS <= 200)
)

DROP TABLE MOVIE;


INSERT INTO MOVIE
VALUES(10, 'Billy', 'Franco Zeiffirelli', 1981, 120);

INSERT INTO MOVIE
VALUES(11, 'Florence: Days of Destruction', 'Franco Zeiffirelli', 1966, 100);

INSERT INTO MOVIE
VALUES(12, 'The Taming of the Shrew', 'Franco Zeiffirelli', 1967, 90);

INSERT INTO MOVIE
VALUES(13, 'Hamlet', 'Franco Zeiffirelli', 1990, 130);

INSERT INTO MOVIE
VALUES(14, 'Born on the Fourth of Jly', 'Oliver Stone', 1989, 124);

INSERT INTO MOVIE
VALUES(15, 'Wall Street', 'Oliver Stone', 1987, 90);

INSERT INTO MOVIE
VALUES(16, 'JFK', 'Oliver Stone' , 1991, 134);

INSERT INTO MOVIE
VALUES(17, 'Zebrahead' , 'Oliver Stone', 1992, 92);

INSERT INTO MOVIE
VALUES(18, 'Space Station 3D', 'Toni Myers', 2002, 142);

INSERT INTO MOVIE
VALUES(19, 'Blue Planet', 'Toni Myers', 1990, 89);

INSERT INTO MOVIE
VALUES(20, 'Destiny in Space', 'Toni Myers', 1994, 78);

INSERT INTO MOVIE
VALUES(21, 'Hubble', 'Toni Myers', 2010, 100);

SELECT *FROM MOVIE;



CREATE TABLE MOVIE_STAT(
MOVIE_ID NUMBER,
CONSTRAINT MOVIE_STAT_ID PRIMARY KEY(MOVIE_ID),
RATING NUMBER(3,1) CHECK(RATING >0 AND RATING < 11),
DOMESTIC_SALES NUMBER,
INTERNATIONAL_SALES NUMBER
)

SELECT *FROM MOVIE;

INSERT INTO MOVIE_STAT
VALUES(10, 8, 1000, 800);

INSERT INTO MOVIE_STAT
VALUES(11, 7, 800, 1500);

INSERT INTO MOVIE_STAT
VALUES(12, 10, 20000, 34000);

INSERT INTO MOVIE_STAT
VALUES(13, 9, 30000, 21000);

INSERT INTO MOVIE_STAT
VALUES(14, 4, 100, 200);

INSERT INTO MOVIE_STAT
VALUES(15, 6, 200, 345);

INSERT INTO MOVIE_STAT
VALUES(16, 8, 3402, 453587);

INSERT INTO MOVIE_STAT
VALUES(17, 7, 568, 2356);

INSERT INTO MOVIE_STAT
VALUES(18, 5, 600, 3459);

INSERT INTO MOVIE_STAT
VALUES(19, 7, 800, 34547);

INSERT INTO MOVIE_STAT
VALUES(20, 10, 10000, 203000);

SELECT *FROM MOVIE_STAT;

SELECT DIRECTOR, COUNT(DIRECTOR) FROM MOVIE
GROUP BY DIRECTOR;

SELECT *FROM MOVIE;

INSERT INTO MOVIE
VALUES(22, 'Jane Eyre', 'Franco Zieffirelli', 1996, 103);

UPDATE MOVIE SET DIRECTOR = 'Franco Zeiffirelli' WHERE ID=22;

SELECT *FROM MOVIE;

INSERT INTO MOVIE
VALUES(23, 'A Beautiful Pianet', 'Toni Myers', 2016, 113);

INSERT INTO MOVIE_STAT
VALUES(22, 8, 45000, 67000);

INSERT INTO MOVIE_STAT
VALUES(23, 7, 36500, 100800);

SELECT DIRECTOR FROM MOVIE
WHERE EXISTS(SELECT  SUM(DOMESTIC_SALES) FROM MOVIE_STAT);
GROUP BY DIRECTOR;

SELECT SUM(DOMESTIC_SALES) FROM MOVIE_STAT
WHERE EXISTS(SELECT DIRECTOR FROM MOVIE WHERE DIRECTOR = 'Toni Myers');


SELECT DIRECTOR, COUNT(DIRECTOR) FROM MOVIE
GROUP BY DIRECTOR;


SELECT SUM(DOMESTIC_SALES) FROM MOVIE_STAT WHERE
EXISTS(SELECT *FROM MOVIE WHERE ID= MOVIE_STAT.MOVIE_ID AND DIRECTOR = 'Franco Zeiffirelli');

SELECT SUM(INTERNATIONAL_SALES) FROM MOVIE_STAT WHERE
EXISTS(SELECT *FROM MOVIE WHERE ID= MOVIE_STAT.MOVIE_ID AND DIRECTOR = 'Franco Zeiffirelli');

SELECT SUM(DOMESTIC_SALES) FROM MOVIE_STAT WHERE
EXISTS(SELECT *FROM MOVIE WHERE ID= MOVIE_STAT.MOVIE_ID AND DIRECTOR = 'Oliver Stone');

SELECT SUM(INTERNATIONAL_SALES) FROM MOVIE_STAT WHERE
EXISTS(SELECT *FROM MOVIE WHERE ID= MOVIE_STAT.MOVIE_ID AND DIRECTOR = 'Oliver Stone');

SELECT SUM(DOMESTIC_SALES) FROM MOVIE_STAT WHERE
EXISTS(SELECT *FROM MOVIE WHERE ID= MOVIE_STAT.MOVIE_ID AND DIRECTOR = 'Toni Myers');

SELECT SUM(INTERNATIONAL_SALES) FROM MOVIE_STAT WHERE
EXISTS(SELECT *FROM MOVIE WHERE ID= MOVIE_STAT.MOVIE_ID AND DIRECTOR = 'Toni Myers');







SELECT DOMESTIC_SALES FROM MOVIE_STAT WHERE
EXISTS(SELECT *FROM MOVIE WHERE ID= MOVIE_STAT.MOVIE_ID AND DIRECTOR = 'Oliver Stone');


SELECT *FROM MOVIE;


SELECT *FROM MOVIE
ORDER BY YEAR DESC;

SELECT *FROM MOVIE
ORDER BY YEAR ASC;

SELECT *FROM MOVIE_STAT
ORDER BY INTERNATIONAL_SALES DESC;