SELECT *FROM ORDERS;

DELETE FROM ORDERS;

DROP TABLE ORDERS;

CREATE TABLE ORDERS(
ID NUMBER CHECK(ID<=1000),
CONSTRAINT ORDER_ID PRIMARY KEY(ID),
USER_ID NUMBER UNIQUE,
ROOM_ID NUMBER UNIQUE,
DATE_FROM TIMESTAMP,
DATE_TO TIMESTAMP,
MONEY_PAIDN NUMBER(10,2)
)

CREATE TABLE HOTEL(
ID NUMBER,
CONSTRAINT HOTEL_ID PRIMARY KEY(ID),
COUNTRY VARCHAR2(50) DEFAULT 'N/A',
CONSTRAINT COUNRY_CHECK CHECK(COUNTRY!='Romania' AND COUNTRY!='Belgium' AND COUNTRY!='China' AND COUNTRY != 'Ukraine'),
CITY VARCHAR2(50) NOT NULL,
STREET VARCHAR2(50)
)
